title: "Philip A. LeMaitre"
logo: "/assets/images/IMG_0184.JPG"
description: "Doctoral Researcher â€¢ Notes on quantum ML, agency, and foundations"
url: "https://antiphoton47.github.io"   # change to your domain later
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "dark"           # try: default, air, dark, neon, mint, sunrise

permalink: /:categories/:title/
breadcrumbs: true

enable_copy_code_button: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-archives

author:
  name: "Philip A. LeMaitre"
  avatar: "/assets/images/IMG_2215.JPG"
  bio: "Research Interests: Quantum Machine Learning, Quantum Foundations, Artificial Intelligence, Quantum Gravity, Relativistic Quantum Information."
  location: "Earth"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:Philip.Lemaitre@uibk.ac.at"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/AntiPhoton47"
    - label: "Google Scholar"
      icon: "fas fa-graduation-cap"
      url: "https://scholar.google.ca/citations?hl=en&user=mw53fQgAAAAJ"
    - label: "ORCID"
      icon: "fab fa-orcid"
      url: "https://orcid.org/0000-0002-0414-5202"
    - label: "LinkedIn"
      icon: "fa-brands fa-linkedin-in"
      url: "www.linkedin.com/in/phil-lemaitre"
    - label: "BlueSky"
      icon: "fa-brands fa-bluesky"
      url: "https://bsky.app/profile/contextguy.bsky.social"
    - label: "X"
      icon: "fa-brands fa-x-twitter"
      url: "https://x.com/Philontre"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

paginate: 8
paginate_path: /page:num/
search: true

feed:
  path: feed.xml

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
